Switch to using stack for building

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,26 +4,77 @@ cache:
   directories:
   - $HOME/.cabal
   - $HOME/.ghc
+  - $HOME/.stack
 before_cache:
 - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
 - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+
+matrix:
+  include:
+  ## We grab the appropriate GHC and cabal-install versions from hvr's PPA. See:
+  ## https://github.com/hvr/multi-ghc-travis
+  #- env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24 HAPPYVER=1.19.5 ALEXVER=3.1.7
+    #compiler: ": #GHC 8.0.1"
+    #addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}
+
+  ## Build with the newest GHC and cabal-install. This is an accepted failure,
+  ## see below.
+  #- env: BUILD=cabal GHCVER=head  CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
+    #compiler: ": #GHC HEAD"
+    #addons: {apt: {packages: [cabal-install-head,ghc-head,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}
+
+  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
+  # variable, such as using --stack-yaml to point to a different file.
+  - env: BUILD=stack ARGS=""
+    compiler: ": #stack default"
+    addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
+
+  # Nightly builds are allowed to fail
+  - env: BUILD=stack ARGS="--resolver nightly"
+    compiler: ": #stack nightly"
+    addons: {apt: {packages: [libgmp,libgmp-dev]}}
+
+  allow_failures:
+  - env: BUILD=cabal GHCVER=head  CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
+  - env: BUILD=stack ARGS="--resolver nightly"
+
 addons:
-  apt:
-    sources:
-    - hvr-ghc
-    packages:
-    - cabal-install-1.22
-    - ghc-7.10.1
   ssh_known_hosts: travispoulsen.com
-env:
-- - CABALVER=1.22
-  - GHCVER=7.10.1
+
 before_install:
   - bash _scripts/pre_install.sh
+  - unset CC
   - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 install:
   - bash _scripts/install.sh
 script:
-  - cabal run build
+- |
+  set -ex
+  case "$BUILD" in
+    stack)
+      stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
+      ;;
+    cabal)
+      cabal install --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES
+
+      ORIGDIR=$(pwd)
+      for dir in $PACKAGES
+      do
+        cd $dir
+        cabal check || [ "$CABALVER" == "1.16" ]
+        cabal sdist
+        PKGVER=$(cabal info . | awk '{print $2;exit}')
+        SRC_TGZ=$PKGVER.tar.gz
+        cd dist
+        tar zxfv "$SRC_TGZ"
+        cd "$PKGVER"
+        cabal configure --enable-tests
+        cabal build
+        cabal test
+        cd $ORIGDIR
+      done
+      ;;
+  esac
+  set +ex
 after_success:
   - bash _scripts/deploy.sh
